name: Build Latest and Release

on:
  workflow_dispatch:
    inputs:
      doRelease:
        description: 'Publish new release'
        type: boolean
        default: false
        required: false
      tag:
        type: string
        description: 'Release version tag (e.g. v1.2.3)'
        required: true
      ref:
        type: string
        description: 'Git ref from which to release'
        required: true
        default: 'main'

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Check runner architecture
        run: uname -m

      - name: Check-out repository
        uses: actions/checkout@v1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt
          architecture: 'arm64'
      
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install nuitka

      - name: Build Executable with Nuitka
        run: |
          python -m nuitka --onefile --assume-yes-for-downloads --output-dir=dist --macos-target-arch=arm64 gofilecli.py
          python -m nuitka --onefile --assume-yes-for-downloads --output-dir=dist_x86_64 --macos-target-arch=x86_64 gofilecli.py

      - name: Upload Artifact [osx-arm64]
        uses: actions/upload-artifact@v3.1.3
        with:
          name: GoFileCLI_osx-x64
          path: dist_x86_64/gofilecli.bin
      
      - name: Upload Artifact [osx-arm64]
        uses: actions/upload-artifact@v3.1.3
        with:
          name: GoFileCLI_osx-arm64
          path: dist/gofilecli.bin

  download:
    runs-on: ubuntu-latest
    needs: [build-macos]
    steps:
      - name: Fetch executables
        uses: actions/download-artifact@v3
      - name: List Files
        run: |
          ls -la